### ISSUE TITLE
ESP822 Arduino

### ISSUE THREAD

**Issue by pgollor** [igrr/mkspiffs#12]
Hi Igrr,

sorry for the post here, but i have to tell you something. And i didn't find any other way to contact you. No mail address and private message @ esp8266.com didn't work too. And i don't use facebook, twitter or so.
And i think its better to post it here and not in the esp8266 project.

My time is currently very limited because I am at the end of my studies.
And therefore i have no time for the esp8266 arudino project in the next months.
And sorry for my absence in the past.

You make a great work with the esp8266 project, but you can remove me from the collaborator list.
I would like to continue, but i lack the time.

Best regards
pgollor

**Comment by igrr** [comment]
Thank you for your help, and good luck with your studies!
