### ISSUE TITLE
MKSPIFFS Images cannot be mounted -- corrupted

### ISSUE THREAD

**Issue by weswitt** [igrr/mkspiffs#37]
The current version of MKSPIFFS produces images that are incompatible with current SPIFFS. Specifically I am flashing a SPIFFS image to a ESP8266 running the Arduino cores code. With images produced by MKSPIFFS the filesystem will not mount.

What is happening is that spiffs_obj_lu_scan is returning SPIFFS_ERR_NOT_A_FS when called from SPIFFS_mount. The tool is creating filesystems with too many unerased blocks.

If I try to mount the fs with SPIFFS built with SPIFFS_USE_MAGIC set to zero then the mount will succeed but reading data from the files will fail. Reads will return zero data.

SPIFFSImpl: allocating 512+240+1400=2152 bytes
SPIFFSImpl: mounting fs @eb000, size=10000, block=1000, page=100
SPIFFS_mount sz:0 logpgsz:256 logblksz:0 perasz:0 addr:00000000 fdsz:240 cachesz:1400
SPIFFSImpl: mount rc=-10025

**Comment by weswitt** [comment]
I did a test that demonstrates the problem and attached some files to show the issue. The zip file has 2 files: fs-bad.bin and fs-good.bin. fs-bad.bin was created by mkspiffs. fs-good.bin was created by the spiffs code in the sketch below.


#include "FS.h"

void read_file()
{
    File configFile = SPIFFS.open("/test.txt", "r");
    if (!configFile)
    {
        Serial.println("cannot open file");
    }
    else
    {
        size_t configSize = configFile.size();
        char buf[512];
        memset(buf, 0, 512);
        size_t bytes_read = configFile.readBytes(buf, configSize);
        configFile.close();
        Serial.print("BYTES_READ: ["); Serial.print(bytes_read); Serial.println("]");
        Serial.print("DATA: ["); Serial.print(buf); Serial.println("]");
    }
}

void write_file()
{
    char buf[512];
    SPIFFS.format();
    strcpy(buf, "*** ==> test data <== *****");
    File f = SPIFFS.open("/test.txt", "w");
    f.write((const uint8_t*)buf, strlen(buf));
    f.close();
    Serial.println("filesystem created");
}

void setup()
{
    Serial.begin(115200);
    //Serial.setDebugOutput(true);
    delay(5000);
    SPIFFS.begin();
    String str = "";
    Serial.println("FILES:");
    Dir dir = SPIFFS.openDir("/");
    while (dir.next())
    {
        str += dir.fileName();
        str += " : ";
        str += dir.fileSize();
        str += "\r\n";
    }
    Serial.print(str);
    write_file();
    read_file();
}

void loop()
{
}

[fs.zip](https://github.com/igrr/mkspiffs/files/1610417/fs.zip)

**Comment by weswitt** [comment]
I resolved this. I built with SPIFFS_USE_MAGIC_LENGTH=0 and SPIFFS_ALIGNED_OBJECT_INDEX_TABLES=1 and it now works.

**Comment by ZXTube** [comment]
For me, I built it with this flag: -DSPIFFS_OBJ_META_LEN=4

note, this is to be able to unpack a spiffs image from an esp32
