### ISSUE TITLE
error when trying to make the project

### ISSUE THREAD

**Issue by ef1986** [igrr/mkspiffs#42]
Dear Mr. Grokhotkov, 

When I tried to make this project, I got an error saying that the file “spiffs.h” could not be found. I can I use the one contained in the ESP-IDF?

Best regards

**Comment by igrr** [comment]
Perhaps you cloned without the submodule? Try doing `git submodule update --init` to pull SPIFFS submodule.

**Comment by ef1986** [comment]
Thanks for the hint! That did the trick!
