### ISSUE TITLE
Windows help

### ISSUE THREAD

**Issue by zafrirron** [igrr/mkspiffs#44]
Windows 10;
Installation run ok (recommend to add comment on zip and diff gnu utils dependency for windows users)
trying to run mkspiffs --version shows that msys-2.0.dll is missing...

**Comment by igrr** [comment]
Can you please try running the release version, and see if any error is generated?
https://github.com/igrr/mkspiffs/releases/tag/0.2.3 (look for *win32.zip archives).

**Comment by zafrirron** [comment]
downloaded the precompiled version
mkspiffs-0.2.3-esp-idf-win32.zip
looks like working (--version for now...), windows defender hates this file however...
