### ISSUE TITLE
Replacing 'diff --strip-trailing-cr'

### ISSUE THREAD

**Issue by b0wter** [igrr/mkspiffs#51]
I am converting most of my toolchains to work in docker containers and the linux distro of choice for me is alpine because of it's small size (4mb base image). However, since it uses busy box for the core components there are usually some workaround required to get things to work.

While trying to get this to work in an alpine container I found that ```diff``` doesnt support the ```--strip-trailing-cr``` parameter. Do you see any difficulties in replacing this with a ```sed```-command and run ```diff``` afterwards?

**Comment by igrr** [comment]
No problem, as long as sed command works with BSD version of sed as well.

**Comment by igrr** [comment]
Merged #52, thanks!
