### ISSUE TITLE
mkspiffs doesn't pack directories recursively

### ISSUE THREAD

**Issue by igrr** [igrr/mkspiffs#7]
Would be usefull for web pages which are usually arranged into a few directories like js/, img/, css/.

**Comment by pgollor** [comment]
Yeah,
it could be useful.
Unfortunately i do not have the time for this at the moment. But I'll try in a few days.

**Comment by igrr** [comment]
This was more of a note to self :) I'll do this, just added an issue in order not to forget.

**Comment by igrr** [comment]
closed with #9, thanks!
